/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

import controlMySql.MySqlConn;
import java.sql.SQLException;
import java.util.Date;

/**
 *
 * @author IZTROW
 */
public class Altas extends javax.swing.JFrame {

    MySqlConn conn;
    Habitacion disponibles[];
    
    public Altas(MySqlConn conn) {
        this.disponibles = new Habitacion[30];
        this.disponibles[0] = new Habitacion(201,1,false);
        this.disponibles[1] = new Habitacion(202,1,false);
        this.disponibles[2] = new Habitacion(203,1,false);
        this.disponibles[3] = new Habitacion(204,1,false);
        this.disponibles[4] = new Habitacion(205,1,false);
        this.disponibles[5] = new Habitacion(206,1,false);
        this.disponibles[6] = new Habitacion(207,1,false);
        this.disponibles[7] = new Habitacion(208,1,false);
        this.disponibles[8] = new Habitacion(209,1,false);
        this.disponibles[9] = new Habitacion(210,1,false);
        this.disponibles[10] = new Habitacion(211,1,false);
        this.disponibles[11] = new Habitacion(212,1,false);
        this.disponibles[12] = new Habitacion(213,1,false);
        this.disponibles[13] = new Habitacion(214,1,false);
        this.disponibles[14] = new Habitacion(215,1,false);
        this.disponibles[15] = new Habitacion(301,1,false);
        this.disponibles[16] = new Habitacion(302,1,false);
        this.disponibles[17] = new Habitacion(303,1,false);
        this.disponibles[18] = new Habitacion(304,1,false);
        this.disponibles[19] = new Habitacion(305,1,false);
        this.disponibles[20] = new Habitacion(306,1,false);
        this.disponibles[21] = new Habitacion(307,1,false);
        this.disponibles[22] = new Habitacion(308,1,false);
        this.disponibles[23] = new Habitacion(309,1,false);
        this.disponibles[24] = new Habitacion(310,1,false);
        this.disponibles[25] = new Habitacion(311,1,false);
        this.disponibles[26] = new Habitacion(312,1,false);
        this.disponibles[27] = new Habitacion(313,1,false);
        this.disponibles[28] = new Habitacion(314,1,false);
        this.disponibles[29] = new Habitacion(315,1,false);
        this.conn = conn;
        initComponents();
        this.revisahab();
    }
    /**
     * Creates new form Altas
     */
            
    public Altas() {
        initComponents();
    }
    private void revisahab(){
        String query;
        for (int i = 0; i < 30; i++) {
            query = "select * from habitaciones where habitacion = " + "'" + this.disponibles[i].numero + "'";
            try{
                this.conn.Consult(query);
                if(!this.conn.rs.getString(1).isEmpty()){
                    
                }
            }catch(SQLException ex){
                this.disponibles[i].libre=true;
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPizarron = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelCuidadOr = new javax.swing.JLabel();
        jLabelTotHuespedes = new javax.swing.JLabel();
        jLabelDias = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jSpinnerDias = new javax.swing.JSpinner();
        jSpinnerHuespedes = new javax.swing.JSpinner();
        jTextFieldCiudad = new javax.swing.JTextField();
        jLabelLema = new javax.swing.JLabel();
        jLabelIngreso = new javax.swing.JLabel();
        jDateChooserIngreso = new com.toedter.calendar.JDateChooser();
        jButtonConfirmar = new javax.swing.JButton();
        jComboBoxTipo = new javax.swing.JComboBox();
        jLabelTipo = new javax.swing.JLabel();
        jLabelHuespedes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPizarron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPizarron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Sitka Small", 0, 60)); // NOI18N
        jLabelTitulo.setText("Registro");
        jPanelPizarron.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 260, 60));

        jLabelCliente.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("Cliente:");
        jPanelPizarron.add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 60));

        jLabelCuidadOr.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelCuidadOr.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCuidadOr.setText("Cuidad de Origen: ");
        jPanelPizarron.add(jLabelCuidadOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 240, 30));

        jLabelTotHuespedes.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelTotHuespedes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotHuespedes.setText("Total de Húespedes:");
        jPanelPizarron.add(jLabelTotHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 270, 40));

        jLabelDias.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelDias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDias.setText("Días de estancia:");
        jPanelPizarron.add(jLabelDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 270, 30));
        jPanelPizarron.add(jTextFieldCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 230, 30));
        jPanelPizarron.add(jSpinnerDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 100, 30));
        jPanelPizarron.add(jSpinnerHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, 30));
        jPanelPizarron.add(jTextFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 130, 30));

        jLabelLema.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelLema.setText("¡Sonria con nosotros!");
        jPanelPizarron.add(jLabelLema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 340, 40));

        jLabelIngreso.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIngreso.setText("Fecha de Ingreso:");
        jPanelPizarron.add(jLabelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 240, 50));
        jPanelPizarron.add(jDateChooserIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 150, 30));

        jButtonConfirmar.setText("Registrar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanelPizarron.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 140, 40));

        jComboBoxTipo.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sencilla", "Doble ", "Triple" }));
        jPanelPizarron.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        jLabelTipo.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipo.setText("Tipo de Habitacion:");
        jPanelPizarron.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabelHuespedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/47093733_539474476553066_5090645292215173120_n.jpg"))); // NOI18N
        jPanelPizarron.add(jLabelHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 830, 526));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelPizarron, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        String nom,origen;
        Date fecha;
        int huespedes,dias;
        nom = this.jTextFieldCliente.getText().trim();
        origen = this.jTextFieldCiudad.getText().trim();
        fecha = this.jDateChooserIngreso.getDate();
        huespedes = Integer.parseInt(this.jSpinnerHuespedes.getValue().toString().trim());
        dias = Integer.parseInt(this.jSpinnerDias.getValue().toString().trim());
        this.dispose();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Altas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooserIngreso;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCuidadOr;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelHuespedes;
    private javax.swing.JLabel jLabelIngreso;
    private javax.swing.JLabel jLabelLema;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotHuespedes;
    private javax.swing.JPanel jPanelPizarron;
    private javax.swing.JSpinner jSpinnerDias;
    private javax.swing.JSpinner jSpinnerHuespedes;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldCliente;
    // End of variables declaration//GEN-END:variables
}
