/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

/**
 *
 * @author IZTROW
 */
public class Altas extends javax.swing.JFrame {

    /**
     * Creates new form Altas
     */
    public Altas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPizarron = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelTipoHab = new javax.swing.JLabel();
        jLabelCuidadOr = new javax.swing.JLabel();
        jLabelTotHuespedes = new javax.swing.JLabel();
        jLabelDias = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jSpinnerDias = new javax.swing.JSpinner();
        jSpinnerHuespedes = new javax.swing.JSpinner();
        jTextFieldCiudad = new javax.swing.JTextField();
        jLabelLema = new javax.swing.JLabel();
        jLabelIngreso = new javax.swing.JLabel();
        jDayChooserCalendario = new com.toedter.calendar.JDayChooser();
        jLabelHuespedes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPizarron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPizarron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Sitka Small", 0, 60)); // NOI18N
        jLabelTitulo.setText("Registro");
        jPanelPizarron.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 260, 60));

        jLabelCliente.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelCliente.setText("Cliente:");
        jPanelPizarron.add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 60));

        jLabelTipoHab.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelTipoHab.setText("Tipo de Habitación:");
        jPanelPizarron.add(jLabelTipoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 270, 50));

        jLabelCuidadOr.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelCuidadOr.setText("Cuidad de Origen: ");
        jPanelPizarron.add(jLabelCuidadOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 240, 30));

        jLabelTotHuespedes.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelTotHuespedes.setText("Total de Húespedes:");
        jPanelPizarron.add(jLabelTotHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 270, 40));

        jLabelDias.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelDias.setText("Días de estancia:");
        jPanelPizarron.add(jLabelDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 270, 30));
        jPanelPizarron.add(jTextFieldCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 230, 30));
        jPanelPizarron.add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 130, 30));
        jPanelPizarron.add(jSpinnerDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 100, 30));
        jPanelPizarron.add(jSpinnerHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, 30));
        jPanelPizarron.add(jTextFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 130, 30));

        jLabelLema.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelLema.setText("¡Sonria con nosotros!");
        jPanelPizarron.add(jLabelLema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 340, 40));

        jLabelIngreso.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelIngreso.setText("Ingreso:");
        jPanelPizarron.add(jLabelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 30));
        jPanelPizarron.add(jDayChooserCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 100));

        jLabelHuespedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/47093733_539474476553066_5090645292215173120_n.jpg"))); // NOI18N
        jPanelPizarron.add(jLabelHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 489, 526));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Altas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDayChooser jDayChooserCalendario;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCuidadOr;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelHuespedes;
    private javax.swing.JLabel jLabelIngreso;
    private javax.swing.JLabel jLabelLema;
    private javax.swing.JLabel jLabelTipoHab;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotHuespedes;
    private javax.swing.JPanel jPanelPizarron;
    private javax.swing.JSpinner jSpinnerDias;
    private javax.swing.JSpinner jSpinnerHuespedes;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
