/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

/**
 *
 * @author IZTROW
 */
public class Bajas extends javax.swing.JFrame {

    /**
     * Creates new form Bajas
     */
    public Bajas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPizarron = new javax.swing.JPanel();
        jLabelCheckOut = new javax.swing.JLabel();
        jLabelLema = new javax.swing.JLabel();
        jLabelNumeroHab = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabelCuenta = new javax.swing.JLabel();
        jLabelDiasEstancia = new javax.swing.JLabel();
        jLabelExtras = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPizarron.setPreferredSize(new java.awt.Dimension(490, 526));
        jPanelPizarron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCheckOut.setFont(new java.awt.Font("Sitka Small", 1, 48)); // NOI18N
        jLabelCheckOut.setText("Check Out");
        jPanelPizarron.add(jLabelCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 270, 70));

        jLabelLema.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabelLema.setForeground(new java.awt.Color(255, 153, 153));
        jLabelLema.setText("¡Vuelva pronto al Paraiso!");
        jPanelPizarron.add(jLabelLema, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 60));

        jLabelNumeroHab.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelNumeroHab.setText("Numero de Habitación:");
        jPanelPizarron.add(jLabelNumeroHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, 50));
        jPanelPizarron.add(jTextFieldNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 100, 30));

        jLabelCuenta.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelCuenta.setText("Cuenta:");
        jPanelPizarron.add(jLabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));

        jLabelDiasEstancia.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelDiasEstancia.setText("Dias de Estancia:");
        jPanelPizarron.add(jLabelDiasEstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 30));

        jLabelExtras.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelExtras.setText("Cargos Extra:");
        jPanelPizarron.add(jLabelExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 190, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/47073000_539474563219724_1011172439784161280_n.jpg"))); // NOI18N
        jPanelPizarron.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCheckOut;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelDiasEstancia;
    private javax.swing.JLabel jLabelExtras;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLema;
    private javax.swing.JLabel jLabelNumeroHab;
    private javax.swing.JPanel jPanelPizarron;
    private javax.swing.JTextField jTextFieldNum;
    // End of variables declaration//GEN-END:variables
}
