/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfWriter;
import controlMySql.MySqlConn;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author IZTROW
 */
public class Bajas extends javax.swing.JFrame {

    MySqlConn conn;
    int tot;
    boolean ext[];
    /**
     * Creates new form Bajas
     * @param conn
     */
    public Bajas(MySqlConn conn) {
        this.conn = conn;
        this.tot = 0;
        this.ext = new boolean[5];
        initComponents();
    }
    public Bajas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPizarron = new javax.swing.JPanel();
        jLabelCheckOut = new javax.swing.JLabel();
        jLabelLema = new javax.swing.JLabel();
        jLabelNumeroHab = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabelCuenta = new javax.swing.JLabel();
        jLabelDiasEstancia = new javax.swing.JLabel();
        jLabelExtras = new javax.swing.JLabel();
        jCheckBoxHab = new javax.swing.JCheckBox();
        jCheckBoxBar = new javax.swing.JCheckBox();
        jCheckBoxTint = new javax.swing.JCheckBox();
        jCheckBoxNiñera = new javax.swing.JCheckBox();
        jCheckBoxSPA = new javax.swing.JCheckBox();
        jLabelCuenta2 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jButtonBaja = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPizarron.setPreferredSize(new java.awt.Dimension(490, 526));
        jPanelPizarron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCheckOut.setFont(new java.awt.Font("Sitka Small", 1, 48)); // NOI18N
        jLabelCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCheckOut.setText("Check Out");
        jPanelPizarron.add(jLabelCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 270, 70));

        jLabelLema.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabelLema.setForeground(new java.awt.Color(234, 223, 223));
        jLabelLema.setText("¡Vuelva pronto al Paraiso!");
        jPanelPizarron.add(jLabelLema, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 60));

        jLabelNumeroHab.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelNumeroHab.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroHab.setText("Numero de Habitación:");
        jPanelPizarron.add(jLabelNumeroHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 310, 50));

        jTextFieldNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNumKeyPressed(evt);
            }
        });
        jPanelPizarron.add(jTextFieldNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 100, 30));

        jLabelCuenta.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCuenta.setText("Cuenta:");
        jPanelPizarron.add(jLabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        jLabelDiasEstancia.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelDiasEstancia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiasEstancia.setText("Nombre del cliente:");
        jPanelPizarron.add(jLabelDiasEstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 260, 30));

        jLabelExtras.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabelExtras.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExtras.setText("Cargos Extra:");
        jPanelPizarron.add(jLabelExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 50));

        jCheckBoxHab.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jCheckBoxHab.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxHab.setText("Servicio a la Habitacion");
        jCheckBoxHab.setContentAreaFilled(false);
        jCheckBoxHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHabActionPerformed(evt);
            }
        });
        jPanelPizarron.add(jCheckBoxHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jCheckBoxBar.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jCheckBoxBar.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxBar.setText("Servicio de Bar");
        jCheckBoxBar.setContentAreaFilled(false);
        jCheckBoxBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBarActionPerformed(evt);
            }
        });
        jPanelPizarron.add(jCheckBoxBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jCheckBoxTint.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jCheckBoxTint.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTint.setText("Servicio de Tintoreria");
        jCheckBoxTint.setContentAreaFilled(false);
        jCheckBoxTint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTintActionPerformed(evt);
            }
        });
        jPanelPizarron.add(jCheckBoxTint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 250, -1));

        jCheckBoxNiñera.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jCheckBoxNiñera.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxNiñera.setText("Servicio de Niñera");
        jCheckBoxNiñera.setContentAreaFilled(false);
        jCheckBoxNiñera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNiñeraActionPerformed(evt);
            }
        });
        jPanelPizarron.add(jCheckBoxNiñera, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jCheckBoxSPA.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jCheckBoxSPA.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSPA.setText("Servicio de SPA");
        jCheckBoxSPA.setContentAreaFilled(false);
        jCheckBoxSPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSPAActionPerformed(evt);
            }
        });
        jPanelPizarron.add(jCheckBoxSPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabelCuenta2.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabelCuenta2.setForeground(new java.awt.Color(255, 255, 255));
        jPanelPizarron.add(jLabelCuenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 310, 30));

        jLabelNom.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(255, 255, 255));
        jPanelPizarron.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 270, 30));

        jButtonBaja.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButtonBaja.setText("Realizar la baja");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });
        jPanelPizarron.add(jButtonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/47073000_539474563219724_1011172439784161280_n.jpg"))); // NOI18N
        jPanelPizarron.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 770, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumKeyPressed
        // TODO add your handling code here:
        this.tot = 0;
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.jCheckBoxBar.setSelected(false);
            this.jCheckBoxSPA.setSelected(false);
            this.jCheckBoxHab.setSelected(false);
            this.jCheckBoxNiñera.setSelected(false);
            this.jCheckBoxTint.setSelected(false);
            int hab;
            String query;
            hab = Integer.parseInt(this.jTextFieldNum.getText().trim());
            query = "SELECT * FROM habitaciones WHERE habitaciones.habitacion = '" + hab + "'";
            this.conn.Consult(query);
            try{
                String nombre = this.conn.rs.getString(1);
                this.jLabelNom.setText(nombre);
                System.out.println(nombre);
                switch(this.conn.rs.getString(4)){
                    case "1":
                        this.tot += 600 * Integer.parseInt(this.conn.rs.getString(5));
                        break;
                    case "2":
                        this.tot += 700 * Integer.parseInt(this.conn.rs.getString(5));
                        break;
                    case "3":
                        this.tot += 800 * Integer.parseInt(this.conn.rs.getString(5));
                        break;
                }
                if(Integer.parseInt(this.conn.rs.getString(7)) > Integer.parseInt(this.conn.rs.getString(4))){
                    tot += ((Integer.parseInt(this.conn.rs.getString(7))-Integer.parseInt(this.conn.rs.getString(4)))*150)*Integer.parseInt(this.conn.rs.getString(5));
                }
                this.jLabelCuenta2.setText(""+tot);
            }catch(SQLException ex){
                System.out.println("Habitacion no ocupada");
            }
        }
    }//GEN-LAST:event_jTextFieldNumKeyPressed

    private void jCheckBoxNiñeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNiñeraActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBoxNiñera.isSelected()){
            this.tot += 200;
            this.ext[0] = true;
        }else{
            this.tot -= 200;
            this.ext[0] = false;
        }
        this.jLabelCuenta2.setText(""+tot);
    }//GEN-LAST:event_jCheckBoxNiñeraActionPerformed

    void recibo(){
        String query = "SELECT * FROM habitaciones WHERE habitaciones.habitacion = '"
                + "" + Integer.parseInt(this.jTextFieldNum.getText().trim())  + "'";
        try {
            String nom;
            nom = this.conn.rs.getString(1);
            Font fuente1, fuente2, fuente3, fuente4, fuente5;
            fuente1 = FontFactory.getFont(FontFactory.TIMES_ROMAN, 22);
            fuente1.setColor(new BaseColor(112, 8, 8));
            
            fuente2 = FontFactory.getFont(FontFactory.TIMES_ROMAN, 22);
            fuente2.setColor(new BaseColor(112, 8, 8));  
            
            fuente3 = FontFactory.getFont(FontFactory.TIMES_ROMAN, 23);
            fuente3.setColor(BaseColor.BLACK);
            
            fuente4 = FontFactory.getFont(FontFactory.TIMES_ROMAN, 20);
            fuente4.setColor(BaseColor.DARK_GRAY);
            
            fuente5 = FontFactory.getFont(FontFactory.TIMES_ROMAN, 18);
            fuente5.setColor(BaseColor.GRAY);
            
            Rectangle tam = new Rectangle(PageSize.LETTER);
            tam.setBackgroundColor(new BaseColor(255, 255, 190));
            Document document = new Document(tam);
            
            PdfWriter.getInstance(document, new FileOutputStream("Recibo.pdf"));
            document.open();
            Image logo = Image.getInstance("src/Imagenes/12RosasPequeño.png");
            logo.scaleAbsolute(220f, 170f);
            logo.setAlignment(Element.ALIGN_CENTER);
            
            document.add(logo);
            String nombre = "\nHuesped: " + nom;
            String ciudad = "Ciudad de Origen: " + this.conn.rs.getString(3) + "\n";
            String fechaI = "Fecha de ingreso: " + this.conn.rs.getString(6) + "\n";
            Date ap;
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            ap = formato.parse(this.conn.rs.getString(6));
            Calendar aux = Calendar.getInstance();
            aux.setTime(ap);
            aux.add(Calendar.DATE,Integer.parseInt(this.conn.rs.getString(5)));
            ap = aux.getTime();
            String fechaS = "Fecha de salida: " + formato.format(ap) + "" +"\n";
            String num = "Habitacion: " + this.conn.rs.getString(2) + "\n";
            int costos = 0;
            switch(this.conn.rs.getString(4)){
                    case "1":
                        costos += 600;
                        break;
                    case "2":
                        costos += 700;
                        break;
                    case "3":
                        costos += 800;
                        break;
                }
            String costo = "Costo por noche: " + costos + "\n";
            String dias = "Dias de hospedaje: " + this.conn.rs.getString(5) +" \n";
            String total = "Total sin cargos extra: " + (Integer.parseInt(this.conn.rs.getString(5)) * costos) + "\n";
            String totalT = "Total a pagar: " + tot + "\n";
            String cargos = "Cargos extras:\n";
            String mensaje = "Hotel 12 Rosas \n 12 razones para ser feliz. ";
            Date fecha2= new Date();
            formato= new SimpleDateFormat("dd/MM/yyy");
            String lugar = "\nMerida Yucatan 97000, "+formato.format(fecha2)+"\n";
            
            Paragraph paragraph;
            //Datos del hotel
            paragraph = new Paragraph(mensaje, fuente1);
            paragraph.setAlignment(Element.ALIGN_CENTER);
            document.add(paragraph);
            //Lugar y fecha
            paragraph = new Paragraph(lugar, fuente4);
            paragraph.setAlignment(Element.ALIGN_RIGHT);
            document.add(paragraph); 
            //Nombre
            paragraph = new Paragraph(nombre, fuente3);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            //Contenido
            paragraph = new Paragraph(ciudad, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph(fechaI, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph(fechaS, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph(num, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph(costo, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph(dias, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph(total, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph(totalT, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            //Cargos Extras
            if(this.ext[0] == true){
                cargos += "Servicio de niñera.\n";
            }
            if(this.ext[1] == true){
                cargos += "Servicio a la habitacion.\n";
            }
            if(this.ext[2] == true){
                cargos += "Servicio de tintoreria.\n";
            }
            if(this.ext[3] == true){
                cargos += "Servicio de SPA.\n";
            }
            if(this.ext[4] == true){
                cargos += "Servicio de bar.\n";
            }
            paragraph = new Paragraph(cargos, fuente5);
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            //Despedida
            String dir = "Un gusto tenerlo con nosotros";
            paragraph = new Paragraph(dir, fuente4);
            paragraph.setAlignment(Element.ALIGN_CENTER);
            document.add(paragraph);
            
            document.close();
            JOptionPane.showMessageDialog(this,"Recibo creado.");
        } catch (DocumentException | IOException | SQLException e) {
            e.printStackTrace();
        } catch (ParseException ex) {
            Logger.getLogger(Bajas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        // TODO add your handling code here:
        String hab = this.jTextFieldNum.getText().trim();
        String query;
        int cuenta = 0;
        if(hab.isEmpty()){
            JOptionPane.showMessageDialog(this,"Numero de Habitacion vacio");
        }else{
            recibo();
            query = "DELETE FROM habitaciones WHERE habitaciones.habitacion = " + hab;
            int j = this.conn.Update(query);
            if(j>0){
                JOptionPane.showMessageDialog(this,"Baja realizada");           
            }else{
                JOptionPane.showMessageDialog(this,"La baja no se pudo realizar");
                return;
            }
        query = "SELECT * FROM habitaciones WHERE habitaciones.habitacion = '1'";
        this.conn.Consult(query);
        query = "UPDATE `tothab` SET `libre` = '1' WHERE `tothab`.`num` = "+ hab;
        this.conn.Update(query);
            try {
                cuenta = Integer.parseInt(this.conn.rs.getString(7));
            } catch (SQLException ex) {
                Logger.getLogger(Bajas.class.getName()).log(Level.SEVERE, null, ex);
            }
        cuenta+=tot;
        query = "UPDATE `habitaciones` SET `totalOcup` = '"+ cuenta +"' WHERE `habitaciones`.`habitacion` = 1 ";
        this.conn.Update(query);
        this.dispose();
        }
        
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jCheckBoxHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHabActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBoxHab.isSelected()){
            this.tot += 300;
            this.ext[1] = true;
        }else{
            this.tot -= 300;
            this.ext[1] = false;
        }
        this.jLabelCuenta2.setText(""+tot);
    }//GEN-LAST:event_jCheckBoxHabActionPerformed

    private void jCheckBoxTintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTintActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBoxTint.isSelected()){
            this.tot += 100;
            this.ext[2] = true;
        }else{
            this.tot -= 100;
            this.ext[2] = false;
        }
        this.jLabelCuenta2.setText(""+tot);
    }//GEN-LAST:event_jCheckBoxTintActionPerformed

    private void jCheckBoxSPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSPAActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBoxSPA.isSelected()){
            this.tot += 300;
            this.ext[3] = true;
        }else{
            this.tot -= 300;
            this.ext[3] = false;
        }
        this.jLabelCuenta2.setText(""+tot);
    }//GEN-LAST:event_jCheckBoxSPAActionPerformed

    private void jCheckBoxBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBarActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBoxBar.isSelected()){
            this.tot += 250;
            this.ext[4] = true;
        }else{
            this.tot -= 250;
            this.ext[4] = false;
        }
        this.jLabelCuenta2.setText(""+tot);
    }//GEN-LAST:event_jCheckBoxBarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bajas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JCheckBox jCheckBoxBar;
    private javax.swing.JCheckBox jCheckBoxHab;
    private javax.swing.JCheckBox jCheckBoxNiñera;
    private javax.swing.JCheckBox jCheckBoxSPA;
    private javax.swing.JCheckBox jCheckBoxTint;
    private javax.swing.JLabel jLabelCheckOut;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelCuenta2;
    private javax.swing.JLabel jLabelDiasEstancia;
    private javax.swing.JLabel jLabelExtras;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLema;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNumeroHab;
    private javax.swing.JPanel jPanelPizarron;
    private javax.swing.JTextField jTextFieldNum;
    // End of variables declaration//GEN-END:variables
}
