/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

import controlMySql.MySqlConn;
import java.sql.SQLException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Julio
 */
public class OcupTip extends javax.swing.JFrame {

    MySqlConn conn;
    Habitacion disponibles[];
    /**
     * Creates new form OcupTip
     * @param conn
     */
    public OcupTip(MySqlConn conn,int tipo) {
        this.conn = conn;
        this.disponibles = new Habitacion[30];
        this.disponibles[0] = new Habitacion(201,1,false);
        this.disponibles[1] = new Habitacion(202,1,false);
        this.disponibles[2] = new Habitacion(203,1,false);
        this.disponibles[3] = new Habitacion(204,1,false);
        this.disponibles[4] = new Habitacion(205,1,false);
        this.disponibles[5] = new Habitacion(206,1,false);
        this.disponibles[6] = new Habitacion(207,2,false);
        this.disponibles[7] = new Habitacion(208,2,false);
        this.disponibles[8] = new Habitacion(209,2,false);
        this.disponibles[9] = new Habitacion(210,2,false);
        this.disponibles[10] = new Habitacion(211,2,false);
        this.disponibles[11] = new Habitacion(212,3,false);
        this.disponibles[12] = new Habitacion(213,3,false);
        this.disponibles[13] = new Habitacion(214,3,false);
        this.disponibles[14] = new Habitacion(215,3,false);
        this.disponibles[15] = new Habitacion(301,1,false);
        this.disponibles[16] = new Habitacion(302,1,false);
        this.disponibles[17] = new Habitacion(303,1,false);
        this.disponibles[18] = new Habitacion(304,1,false);
        this.disponibles[19] = new Habitacion(305,2,false);
        this.disponibles[20] = new Habitacion(306,2,false);
        this.disponibles[21] = new Habitacion(307,2,false);
        this.disponibles[22] = new Habitacion(308,2,false);
        this.disponibles[23] = new Habitacion(309,2,false);
        this.disponibles[24] = new Habitacion(310,2,false);
        this.disponibles[25] = new Habitacion(311,3,false);
        this.disponibles[26] = new Habitacion(312,3,false);
        this.disponibles[27] = new Habitacion(313,3,false);
        this.disponibles[28] = new Habitacion(314,3,false);
        this.disponibles[29] = new Habitacion(315,3,false);
        initComponents();
        revisahab();
        creaGraficas(tipo);
    }
    public OcupTip() {
        initComponents();
    }

    public void creaGraficas(int tipo){
        int lib = 0;
        int ocup = 0;
        for (int i = 0; i < disponibles.length; i++) {
            if(this.disponibles[i].tipo == tipo && this.disponibles[i].libre == true){
                lib++;
            }else if(this.disponibles[i].tipo == tipo){
                ocup++;
            }
        }
        DefaultPieDataset data = new DefaultPieDataset();
        data.setValue("Libre", (lib*100)/this.disponibles.length);
        data.setValue("Ocupado", (ocup*100)/this.disponibles.length);

        JFreeChart chart = ChartFactory.createPieChart(
         "Porcentaje de ocupacion de habitaciones tipo " + tipo + ".", data);

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setBounds(200,25,350,350);
        chartPanel.setVisible(true);
        this.jPanel1.add(chartPanel);
    }
    private void revisahab() {
        String query;
        for (int i = 0; i < 30; i++) {
            query = "select * from habitaciones where habitacion = " + "'" + this.disponibles[i].numero + "'";
            try {
                this.conn.Consult(query);
                if (!this.conn.rs.getString(1).isEmpty()) {

                }
            } catch (SQLException ex) {
                this.disponibles[i].libre = true;
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(627, 409));
        setMinimumSize(new java.awt.Dimension(627, 409));

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 333, 160, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OcupTip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OcupTip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OcupTip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OcupTip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OcupTip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
