/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

import controlMySql.MySqlConn;
import java.sql.SQLException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Julio
 */
public class OcupTip extends javax.swing.JFrame {

    MySqlConn conn;
    Habitacion disponibles[];
    /**
     * Creates new form OcupTip
     * @param conn
     */
    public OcupTip(MySqlConn conn,int tipo) {
        this.conn = conn;
        initComponents();
        revisahab();
        creaGraficas(tipo);
    }
    public OcupTip() {
        initComponents();
    }

    public void creaGraficas(int tipo){
        int lib = 0;
        int ocup = 0;
        for (int i = 0; i < disponibles.length; i++) {
            if(this.disponibles[i].tipo == tipo && this.disponibles[i].libre == 1){
                lib++;
            }else if(this.disponibles[i].tipo == tipo){
                ocup++;
            }
        }
        DefaultPieDataset data = new DefaultPieDataset();
        data.setValue("Libre", (lib));
        data.setValue("Ocupado", (ocup));

        JFreeChart chart = ChartFactory.createPieChart(
         "Porcentaje de ocupacion de habitaciones tipo " + tipo + ".", data);

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setBounds(200,25,350,350);
        chartPanel.setVisible(true);
        this.jPanel1.add(chartPanel);
    }
    private void revisahab() {
        String query;
        int j = 0;
        disponibles = new Habitacion[30];
        int numero,tipo,libre;
        for (int i = 201; i < 216; i++) {
            query = "select * from tothab where num = " + "'" + i + "'";
            try{
                this.conn.Consult(query);
                numero =Integer.parseInt(this.conn.rs.getString(1));
                tipo = Integer.parseInt(this.conn.rs.getString(2));
                libre = Integer.parseInt(this.conn.rs.getString(3));
                this.disponibles[j] = new Habitacion(numero,tipo,libre);
                j++;
            }catch(SQLException ex){
                System.out.println("Error al abrir SQL");
            }
        }
        for (int i = 301; i < 316; i++) {
            query = "select * from tothab where num = " + "'" + i + "'";
            try{
                this.conn.Consult(query);
                numero =Integer.parseInt(this.conn.rs.getString(1));
                tipo = Integer.parseInt(this.conn.rs.getString(2));
                libre = Integer.parseInt(this.conn.rs.getString(3));
                this.disponibles[j] = new Habitacion(numero,tipo,libre);
                j++;
            }catch(SQLException ex){
                System.out.println("Error al abrir SQL");
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(627, 409));
        setMinimumSize(new java.awt.Dimension(627, 409));

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 333, 160, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OcupTip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OcupTip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OcupTip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OcupTip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OcupTip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
