/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

import controlMySql.MySqlConn;
import java.sql.SQLException;

/**
 *
 * @author IZTROW
 */
public class Piso1 extends javax.swing.JFrame {

    Habitacion disponibles[];
    MySqlConn conn;
    /**
     * Creates new form Piso1
     * @param conn
     * @param ps
     */
    public Piso1(MySqlConn conn, int ps) {
        this.conn = conn;
        initComponents();
        revisaHab();
        imprimeHab(ps);
    }
    public Piso1() {
        initComponents();
    }

    private void revisaHab() {
        String query;
        int j = 0;
        disponibles = new Habitacion[30];
        int numero,tipo,libre;
        for (int i = 201; i < 216; i++) {
            query = "select * from tothab where num = " + "'" + i + "'";
            try{
                this.conn.Consult(query);
                numero =Integer.parseInt(this.conn.rs.getString(1));
                tipo = Integer.parseInt(this.conn.rs.getString(2));
                libre = Integer.parseInt(this.conn.rs.getString(3));
                this.disponibles[j] = new Habitacion(numero,tipo,libre);
                j++;
            }catch(SQLException ex){
                System.out.println("Error al abrir SQL");
            }
        }
        for (int i = 301; i < 316; i++) {
            query = "select * from tothab where num = " + "'" + i + "'";
            try{
                this.conn.Consult(query);
                numero =Integer.parseInt(this.conn.rs.getString(1));
                tipo = Integer.parseInt(this.conn.rs.getString(2));
                libre = Integer.parseInt(this.conn.rs.getString(3));
                this.disponibles[j] = new Habitacion(numero,tipo,libre);
                j++;
            }catch(SQLException ex){
                System.out.println("Error al abrir SQL");
            }
        }
    }
    void imprimeHab(int ps){
        this.jTextAreaResultado.setText("");
        this.jTextAreaResultado.append("Habitaciones libres del piso " + ps +  ":\nSencillas: ");
        for (int i = 0; i < this.disponibles.length; i++) {
            if((this.disponibles[i].numero/100)-1 == ps && this.disponibles[i].tipo == 1 && this.disponibles[i].libre == 1){
                this.jTextAreaResultado.append("[" + this.disponibles[i].numero + "] ");
            }
        }
        this.jTextAreaResultado.append("\nDobles: ");
        for (int i = 0; i < this.disponibles.length; i++) {
            if((this.disponibles[i].numero/100)-1 == ps && this.disponibles[i].tipo == 2 && this.disponibles[i].libre == 1){
                this.jTextAreaResultado.append("[" + this.disponibles[i].numero + "] ");
            }
        }
        this.jTextAreaResultado.append("\nTriples: ");
        for (int i = 0; i < this.disponibles.length; i++) {
            if((this.disponibles[i].numero/100)-1 == ps && this.disponibles[i].tipo == 3 && this.disponibles[i].libre == 1){
                this.jTextAreaResultado.append("[" + this.disponibles[i].numero + "] ");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPizarron = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDisponibles = new javax.swing.JLabel();
        jButtonrRegresar = new javax.swing.JButton();
        jScrollPaneResultado = new javax.swing.JScrollPane();
        jTextAreaResultado = new javax.swing.JTextArea();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPizarron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPizarron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 48)); // NOI18N
        jLabel2.setText("Habitaciones ");
        jPanelPizarron.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 370, 50));

        jLabelDisponibles.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabelDisponibles.setText("Disponibles");
        jPanelPizarron.add(jLabelDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 320, 80));

        jButtonrRegresar.setText("REGRESAR");
        jButtonrRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrRegresarActionPerformed(evt);
            }
        });
        jPanelPizarron.add(jButtonrRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 130, 50));

        jTextAreaResultado.setColumns(20);
        jTextAreaResultado.setRows(5);
        jScrollPaneResultado.setViewportView(jTextAreaResultado);

        jPanelPizarron.add(jScrollPaneResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 360, 220));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/47062107_539474499886397_2159788295511343104_n.jpg"))); // NOI18N
        jPanelPizarron.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 810, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPizarron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonrRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonrRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piso1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonrRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDisponibles;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanelPizarron;
    private javax.swing.JScrollPane jScrollPaneResultado;
    private javax.swing.JTextArea jTextAreaResultado;
    // End of variables declaration//GEN-END:variables
}
