/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

/**
 *
 * @author IZTROW
 */
public class Portada extends javax.swing.JPanel {

    /**
     * Creates new form Portada
     */
    public Portada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUAA = new javax.swing.JLabel();
        jLabelMaestra = new javax.swing.JLabel();
        jLabelMateria = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelProgramador1 = new javax.swing.JLabel();
        jLabelProgramadores = new javax.swing.JLabel();
        jLabelProgramador2 = new javax.swing.JLabel();
        jLabelProgramador3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelUAA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UAA.png"))); // NOI18N

        jLabelMaestra.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelMaestra.setText("Maestra: Georgina Salazar Partida");

        jLabelMateria.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelMateria.setText("Materia: Programacion ii");

        jLabelFecha.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelFecha.setText("Fecha:");

        jLabelProgramador1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabelProgramador1.setText("Julio de Jesus Gonzalez Rangel");

        jLabelProgramadores.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelProgramadores.setText("Programadores:");

        jLabelProgramador2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabelProgramador2.setText("Isabel Abigail Bermúdez Navarro");

        jLabelProgramador3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabelProgramador3.setText("Roberto Méndez Correa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabelUAA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProgramadores)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelMaestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelProgramador1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelProgramador2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelProgramador3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUAA, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMaestra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelProgramadores)
                .addGap(18, 18, 18)
                .addComponent(jLabelProgramador1)
                .addGap(18, 18, 18)
                .addComponent(jLabelProgramador2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProgramador3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMaestra;
    private javax.swing.JLabel jLabelMateria;
    private javax.swing.JLabel jLabelProgramador1;
    private javax.swing.JLabel jLabelProgramador2;
    private javax.swing.JLabel jLabelProgramador3;
    private javax.swing.JLabel jLabelProgramadores;
    private javax.swing.JLabel jLabelUAA;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
